[build]
    command = 'npm install && npm run build'

[[redirects]]
    from = "/v2/*"
    to = "/index.html"
    status = 200


[[redirects]]
    from = "/term*"
    to = "/index.html"
    status = 200