[build]
    command = "npm install && npm run build"
    publish = "dist/"

[[redirects]]
    from = "/v2/*"
    to = "/index.html"
    status = 200


[[redirects]]
    from = "/term*"
    to = "/index.html"
    status = 200
